#stack_main: stack_main.o stack.o
#	gcc -o stack_main stack_main.o stack.o
#stack_main.o: stack_main.c stack.h
#	gcc -c -g stack_main.c stack.h
#stack.o: stack.c stack.h
#	gcc -c -g stack.c stack.h
stack_array_main: stack_array_main.o stack_array.o
	gcc -o stack_array_main stack_array_main.o stack_array.o
stack_array_main.o: stack_array_main.c stack_array.h
	gcc -c -g stack_array_main.c stack_array.h
stack_array.o: stack_array.c stack_array.h
	gcc -c -g stack_array.c stack_array.h
